name: Android Build & Release (auto keystore)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }

      - uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK (API 35)
        run: sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0" || true

      - name: Install Gradle
        run: |
          sudo apt-get update && sudo apt-get install -y unzip curl
          curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> "$GITHUB_PATH"
          gradle wrapper
          chmod +x ./gradlew

      - name: Restore or generate keystore
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${ANDROID_KEYSTORE_BASE64:-}" ]; then
            CLEAN="$(printf "%s" "$ANDROID_KEYSTORE_BASE64" | tr -d '\n\r ')"
            echo "$CLEAN" | base64 -d > keystore.jks
            echo "ANDROID_KEYSTORE_ALIAS=${ANDROID_KEYSTORE_ALIAS:-release}" >> "$GITHUB_ENV"
            echo "ANDROID_KEYSTORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD:-android}" >> "$GITHUB_ENV"
            echo "ANDROID_KEY_PASSWORD=${ANDROID_KEY_PASSWORD:-android}" >> "$GITHUB_ENV"
          else
            keytool -genkeypair -v -keystore keystore.jks -storetype PKCS12 -storepass android -keypass android \
              -keyalg RSA -keysize 2048 -validity 3650 -alias release \
              -dname "CN=CI, OU=CI, O=CI, L=Bangkok, ST=TH, C=TH"
            echo "ANDROID_KEYSTORE_ALIAS=release" >> "$GITHUB_ENV"
            echo "ANDROID_KEYSTORE_PASSWORD=android" >> "$GITHUB_ENV"
            echo "ANDROID_KEY_PASSWORD=android" >> "$GITHUB_ENV"
          fi
          echo "ANDROID_KEYSTORE_PATH=$PWD/keystore.jks" >> "$GITHUB_ENV"

      - name: Build Release
        run: ./gradlew --no-daemon clean assembleRelease

      - name: Read versionCode
        id: ver
        run: |
          CODE=$(sed -n 's/.*versionCode[[:space:]]*=[[:space:]]*\([0-9]\+\).*/\1/p' app/build.gradle.kts | head -n1)
          echo "code=$CODE" >> "$GITHUB_OUTPUT"

      # ✅ โชว์ใน Actions > Artifacts ด้วย
      - name: Upload APK (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          retention-days: 7

      # ✅ แนบไปที่ Release ด้วย
      - name: Create/Update GitHub Release (upload APK)
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.ver.outputs.code }}
          name: Release v${{ steps.ver.outputs.code }}
          makeLatest: true
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "app/build/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
